services:
  # magnito:
  #   build:
  #     context: .
  #     args:
  #       - VERSION=0.0.0
  #   ports:
  #     - 5050:5050
  #     - 5051:5051
  #   volumes:
  #     - magnito-data:/usr/src/app/data
  #   depends_on:
  #     inbucket:
  #       condition: service_started

  inbucket:
    image: inbucket/inbucket:3.0.3
    ports:
      - 2500:2500 # SMTP
      - 9000:9000 # web interface
      - 1100:1100 # POP3
    volumes:
      - inbucket:/storage

volumes:
  # magnito-data:
  #   driver: local
  inbucket:
    driver: local
