name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 26
      - uses: actions/cache@v6
        id: npm-cache
        with:
          path: 'node_modules'
          key: npm-${{ hashFiles('package-lock.json') }}
      - run: npm install
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: cp .env.example .env
      - run: npm run generate
      - run: npm run lint
      - run: npm run typecheck
      - run: docker compose --profile test up -d
      - run: npm test

      - run: docker compose up -d inbucket
      - run: docker build . -t magnito --build-arg VERSION=0.0.0
      - run: docker run -d --name debug --network magnito_default magnito
      - run: count=0 && until [ "$(docker inspect --format='{{json .State.Health.Status}}' debug)" == "\"healthy\"" ] || [ $count -eq 30 ]; do sleep 1; count=$((count + 1)); done && [ $count -ne 30 ]
        id: healthcheck
      - if: failure() && steps.healthcheck.outcome == 'failure'
        run: docker logs debug
      - run: docker stop debug
